version: "3.3"

services:
  nats:
    image: nats:2
    networks:
      - internal
    ports:
      - 4222:4222

  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - 6379:6379

  mongo:
    image: mongo:5
    networks:
      - internal
    ports:
      - "27017:27017"

networks:
  internal:

volumes:
  data:
